dist: xenial
sudo: false
language: go
go:
- '1.12'

env:
  global:
    # CODACY_TOKEN
    - secure: "o+zKtnbIXRq8Hpap/ahQ4HvAcrO1xK4QziTfWxppw/IUAcUjlD0t+9lLuOHE2y8FQujhAZqpbduSqhPR8Szruf5QFLr5ckE/lOiOTo+xwSaYGCEii0csvzmFmD2yg4FfWCu6G32cugoXUAAoTY1x2rtcU3fHerhhE9u4+6E79ch/XNasolp0eR9Sje+oRYaCp3O4OfPAAJ5KdREp6zZcmonbNTQVtf2tKCa3mpkPAxmHmLm0fx3oxgc/+AvjQ+gCvxdtJxgqVj97SJ+lPCzJ4IJd+gm61SO4bMFBVaZMfalQdtmms6ZI6XJMz+b4havTORNfNTLl12WOke2NmJ0Y+IJth8/uFQ2DmmxwRMgyF80bKHeYzrdT0i7UO8pvTPm0we+M53YDNAwc/QUEKhFgw/MDKzLZK4hVETTQ60TsdFd0e7ZNl2yGwowLABt2O7O0pe+ACYa3pPFN+ZAblxw5oyuVvHwjz1wVH/K4LbHkKZ22LvS4pTbi6BbO45pAfITpau1aRtL8lUvcluf8ozNcIQxCgoQd9ca+HQQ5JJKU42X+8x4MTZ5jG1o95uJ3EdVgC7n1NMxp/v4jLi8qwg4AXz5OR9OnJI5s2yprE9xL1W5QiBw3zc/yh15rlOOkUJ/bCy+1en6UREP90bWT6X2l6Ei7a6MO0SedNx6MpILmko0="
  - GO111MODULE=on

install:
- make dist
# for reporting coverage to codacy
- go get -u github.com/schrej/godacov

script:
- make test
- if [ -n "${CODACY_TOKEN}" ]; then godacov -t "${CODACY_TOKEN}" -r ./coverage.out -c "${TRAVIS_COMMIT}"; fi

deploy:
  provider: releases
  api_key:
    secure: pkIPTqLLqjvW6Ggp6DzRh2r4OZ0Bg+17Ii8sYq+eA5Nr++/qzOg/OW+phMKyYcAekAC3FMXC9g54SKDmRPBaJn1KoDOLQydh8XVWpxKGdGBOSZdSc/yBJ3TqrQcfk9+rJ3y0VY1kGPboDLD28OXYRUKDUHDBK5ZxJAxwHGe6QUJf3xpg8+H6xQ1wOuvfZABSiD9Mq/dPtO2K6vuzNaiLpNKzcxPu61LXieOrDnF1uQBS0xuTSfoWHSb4diEYOo/un4GAssMslCTrMSj8baz7NaUySMNNFx1sbQWgVSexCFh/uCzAE+WzomFIqFEtCeV1p8tNvOKOC+c1Z6xUoKWk1vQedYGSI1TliYtLtSzFZMYtm9jIW1Gp9Pl1Zy/cWkGeXfocVWwVmCQwN5zLNdeqGgKrhiGO8X/R2YeqHvcQcl8f3YSNdWmHy2kzw4whT8/mNJvl+A9RfiC9Nv8hXeiULTuyUWuhGTzXwck0+LzOC+VseluN0vCMk0ea81FcZy4C4HSCj46BwMLvBxTxw2KHt5BsMvHeHXwHK11FHX3EgTZwa+vVJIMgXlvQ3xdyaXOPxdDcsEDiX06LMLDPUP9Ki+mwFvL6DTXd3+dtHO73tKdgaIM4X+V4yeKxcbBSQPcp5CMqh5WBQKcrDhAD7zXc0DptCsb9sY3TY8pBqcOfkak=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
