dist: trusty
sudo: false
language: go
go:
- '1.11'

env:
  global:
    # CODACY_TOKEN
    - secure: "o+zKtnbIXRq8Hpap/ahQ4HvAcrO1xK4QziTfWxppw/IUAcUjlD0t+9lLuOHE2y8FQujhAZqpbduSqhPR8Szruf5QFLr5ckE/lOiOTo+xwSaYGCEii0csvzmFmD2yg4FfWCu6G32cugoXUAAoTY1x2rtcU3fHerhhE9u4+6E79ch/XNasolp0eR9Sje+oRYaCp3O4OfPAAJ5KdREp6zZcmonbNTQVtf2tKCa3mpkPAxmHmLm0fx3oxgc/+AvjQ+gCvxdtJxgqVj97SJ+lPCzJ4IJd+gm61SO4bMFBVaZMfalQdtmms6ZI6XJMz+b4havTORNfNTLl12WOke2NmJ0Y+IJth8/uFQ2DmmxwRMgyF80bKHeYzrdT0i7UO8pvTPm0we+M53YDNAwc/QUEKhFgw/MDKzLZK4hVETTQ60TsdFd0e7ZNl2yGwowLABt2O7O0pe+ACYa3pPFN+ZAblxw5oyuVvHwjz1wVH/K4LbHkKZ22LvS4pTbi6BbO45pAfITpau1aRtL8lUvcluf8ozNcIQxCgoQd9ca+HQQ5JJKU42X+8x4MTZ5jG1o95uJ3EdVgC7n1NMxp/v4jLi8qwg4AXz5OR9OnJI5s2yprE9xL1W5QiBw3zc/yh15rlOOkUJ/bCy+1en6UREP90bWT6X2l6Ei7a6MO0SedNx6MpILmko0="
    - GO111MODULE=on

install:
- make dist
# for reporting coverage to codacy
- go get -u github.com/schrej/godacov

script:
- make test
- if [ -n "${CODACY_TOKEN}" ]; then godacov -t "${CODACY_TOKEN}" -r ./coverage.out -c "${TRAVIS_COMMIT}"; fi

deploy:
  provider: releases
  api_key:
    secure: i0BILCFie69NAGonBrCAMHVyww538K8cXiz7R3SXvq1ya8DSXwKAFMvnkhTdG9B6Khip4m/ddL7gu3CDDl8vdMXR74SYdL5nsCam7bi0wSJDVwABj1qEI9BtvsPvobw8XTstG/oVcAJitXVkIvaX3nx8BPAxYZBFsLkYehJZhXI/FMMHgJn5NWE7HkBpZHXcUNHzeLckv8D00j80eXbd/WxiSA9+cH/qf91ajYNlJjqDGy5bf1Lhq3qYWk2FVKTzoBi187TtCs26aEvrcUYDnYNlKZHNvTqyyMtxyKwOCugDjvI4Vqua8fiB1JKcg7fvnJeoekQSFVb7J3LsNnJqYOd8iB9kJWKSqRCpaRFQp4R/ubn91ewvahdiTd78yChxO8f1N2ED6KoeMIf/v7PjjWGQydQKtTl5/rgNMPCVyKkvZiV2avAuQB96QqfJ4wt4rU3frroKG6LGWbQ3zyKvHmHXLGiJHAr2+z8mCG8v4XYhc5/fpe3UG/xlFCh1UJj/5mbI9x1HM/sWFZ/U2KXa4euCqE9vH6QT0VDvmG5aXwXonXWtV4Xlw2FQmeRa6CnRSk382HifLFa6hcOkib6vGnRTMZvMuepQx0bD4iYqdsl2Yja67DjFv7MphMFaypf/N+ZxzqYRgD8Hjvp8AONnLhOagJ+kdcvV1MMfdLLKOMY=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
