dist: xenial
sudo: false
language: go
go:
- '1.12'

env:
  global:
    # CODACY_TOKEN
    - secure: "o+zKtnbIXRq8Hpap/ahQ4HvAcrO1xK4QziTfWxppw/IUAcUjlD0t+9lLuOHE2y8FQujhAZqpbduSqhPR8Szruf5QFLr5ckE/lOiOTo+xwSaYGCEii0csvzmFmD2yg4FfWCu6G32cugoXUAAoTY1x2rtcU3fHerhhE9u4+6E79ch/XNasolp0eR9Sje+oRYaCp3O4OfPAAJ5KdREp6zZcmonbNTQVtf2tKCa3mpkPAxmHmLm0fx3oxgc/+AvjQ+gCvxdtJxgqVj97SJ+lPCzJ4IJd+gm61SO4bMFBVaZMfalQdtmms6ZI6XJMz+b4havTORNfNTLl12WOke2NmJ0Y+IJth8/uFQ2DmmxwRMgyF80bKHeYzrdT0i7UO8pvTPm0we+M53YDNAwc/QUEKhFgw/MDKzLZK4hVETTQ60TsdFd0e7ZNl2yGwowLABt2O7O0pe+ACYa3pPFN+ZAblxw5oyuVvHwjz1wVH/K4LbHkKZ22LvS4pTbi6BbO45pAfITpau1aRtL8lUvcluf8ozNcIQxCgoQd9ca+HQQ5JJKU42X+8x4MTZ5jG1o95uJ3EdVgC7n1NMxp/v4jLi8qwg4AXz5OR9OnJI5s2yprE9xL1W5QiBw3zc/yh15rlOOkUJ/bCy+1en6UREP90bWT6X2l6Ei7a6MO0SedNx6MpILmko0="
    - GO111MODULE=on

install:
- make dist
# for reporting coverage to codacy
- go get -u github.com/schrej/godacov

script:
- make test
- if [ -n "${CODACY_TOKEN}" ]; then godacov -t "${CODACY_TOKEN}" -r ./coverage.out -c "${TRAVIS_COMMIT}"; fi

deploy:
  provider: releases
  api_key:
    secure: tZ7eRZ+OmBeCNKZ/o2F21PiwsYP/2iSXwObIo93ZT/wNLGY7m2ai5Mxr4tmBVYiGv8FmSVfIaXV3KfonB98FbleauSD3XH9LFtZZW7u4DOSnTw5NXunACZnncoJNOZX6unyHCNPmH3DHWSwRzYMwX6DtXOw+gWKP7KURuAKWNFPq/p6VdCSIZASIjLKQM/M7Ju6+jepCizwixY97VWZ/Pij554obqLj77C8t/w9QMN4DXmUtsimYl+MrVWal3ySr+2rwZi7M+kh5l45ctxTpSbuQVt0LOyRwO8aU7vlrySDa4Uhk2XEiTGz2R45qwUJhoqik/rUdJACl0Mt+bgGJfhecUdTI1LEwAfLHZmTD+9xnEbHcYu5Rhg/dOBEEwOKKQzaepjj8yOQa5KVxQCs/MEt++V94b/PrpdTFdgZ0ZdErGb0gAwHwXDDp9p5dvWOAvZNyf1v7mllzKWheoWXiQVNdh29YPQpnWatHAbieAIc7ErMod9bBqzHLFaImGwQ89lt7T5pg/M0gCTAEvn8C3VmIjA2g5s65NL9rGB8TC9d8D8onK/MrqvWS5et3JmBeOch/dMmOWNJjrIBDy46d58/gr6OC4TrAkr9tLHq0xnjAUA1cUl1vA1CESzJRwZgbWy7zevrnrMkaLs+SVNlHI/pK8UDr5AMHVXdOR2iYRS0=
  file: dist/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
